package com.combatives.api.camera;

import net.minecraft.entity.Entity;

public final class CameraImpulse {
    private final String effectId; private final Entity sourceEntity; private final boolean hasPosition; private final double x,y,z;
    private final float pitch,yaw,roll,translateX,translateY,translateZ,fov,duration,attackTime,frequency;
    private final CameraDecayType decayType; private final CameraPriority priority; private final CameraStackingMode stackingMode;
    private CameraImpulse(Builder b) { effectId=b.effectId; sourceEntity=b.sourceEntity; hasPosition=b.hasPosition; x=b.x; y=b.y; z=b.z; pitch=b.pitch; yaw=b.yaw; roll=b.roll; translateX=b.translateX; translateY=b.translateY; translateZ=b.translateZ; fov=b.fov; duration=b.duration; attackTime=b.attackTime; decayType=b.decayType; frequency=b.frequency; priority=b.priority; stackingMode=b.stackingMode; }
    public static Builder builder(String effectId) { return new Builder(effectId); }
    public String getEffectId(){return effectId;} public Entity getSourceEntity(){return sourceEntity;} public boolean hasPosition(){return hasPosition;} public double getX(){return x;} public double getY(){return y;} public double getZ(){return z;}
    public float getPitch(){return pitch;} public float getYaw(){return yaw;} public float getRoll(){return roll;} public float getTranslateX(){return translateX;} public float getTranslateY(){return translateY;} public float getTranslateZ(){return translateZ;} public float getFov(){return fov;} public float getDuration(){return duration;} public float getAttackTime(){return attackTime;} public CameraDecayType getDecayType(){return decayType;} public float getFrequency(){return frequency;} public CameraPriority getPriority(){return priority;} public CameraStackingMode getStackingMode(){return stackingMode;}
    public static final class Builder { private final String effectId; private Entity sourceEntity; private boolean hasPosition; private double x,y,z; private float pitch,yaw,roll,translateX,translateY,translateZ,fov,duration=0.35F,attackTime=0.0F,frequency=0.0F; private CameraDecayType decayType=CameraDecayType.SMOOTH; private CameraPriority priority=CameraPriority.NORMAL; private CameraStackingMode stackingMode=CameraStackingMode.ADD;
        private Builder(String effectId){this.effectId=effectId;} public Builder sourceEntity(Entity e){sourceEntity=e;return this;} public Builder position(double x,double y,double z){hasPosition=true;this.x=x;this.y=y;this.z=z;return this;} public Builder rotation(float pitch,float yaw,float roll){this.pitch=pitch;this.yaw=yaw;this.roll=roll;return this;} public Builder translation(float x,float y,float z){translateX=x;translateY=y;translateZ=z;return this;} public Builder fov(float f){fov=f;return this;} public Builder duration(float d){duration=d;return this;} public Builder attackTime(float a){attackTime=a;return this;} public Builder decayType(CameraDecayType d){if(d!=null)decayType=d;return this;} public Builder oscillationFrequency(float f){frequency=f;return this;} public Builder priority(CameraPriority p){if(p!=null)priority=p;return this;} public Builder stackingMode(CameraStackingMode m){if(m!=null)stackingMode=m;return this;} public CameraImpulse build(){return new CameraImpulse(this);} }
}
