package com.glowingfederal.combatives.client.camera.internal;

import com.combatives.api.camera.*;
import com.glowingfederal.combatives.Combatives;
import com.glowingfederal.combatives.config.CombativesConfig;
import net.minecraft.client.Minecraft;
import net.minecraft.client.entity.EntityPlayerSP;
import java.util.*;

public final class CameraEffectManager {
    private static final int MAX_IMPULSES=64, MAX_CONTINUOUS=32; private static final ArrayList<Active> impulses=new ArrayList<Active>(); private static final ArrayList<Handle> continuous=new ArrayList<Handle>(); private static float pitch,yaw,roll,x,y,z,fov;
    private CameraEffectManager(){}
    public static boolean isAvailable(){return Minecraft.getMinecraft()!=null&&CombativesConfig.enableCombativesCamera;}
    public static boolean trigger(CameraEffectType type, CameraEffectContext ctx, float strength){ if(type==null) return reject("missing_type"); strength=safe(strength,0,1); if(strength<=0)return reject("zero_strength"); return submitImpulse(preset(type,ctx,strength)); }
    public static boolean submitImpulse(CameraImpulse in){ if(!isAvailable())return reject("camera_unavailable_or_disabled"); CameraImpulse i=sanitize(in); if(i==null)return false; if(!hasProcessableChannel(i))return reject("no_processable_channels"); if(impulses.size()>=MAX_IMPULSES) impulses.remove(0); if (!resolveStacking(impulses,i)) return false; impulses.add(new Active(i,1)); logDebug("camera API impulse created id="+i.getEffectId()+" pitch="+i.getPitch()+" yaw="+i.getYaw()+" roll="+i.getRoll()+" translation=("+i.getTranslateX()+","+i.getTranslateY()+","+i.getTranslateZ()+") fov="+i.getFov()); return true; }
    static boolean submitImpulseForDevelopmentTest(CameraImpulse in){ CameraImpulse i=sanitize(in); if(i==null||!hasProcessableChannel(i))return false; if (!resolveStacking(impulses,i)) return false; impulses.add(new Active(i,1)); return true; }
    static CameraEffectHandle startContinuousEffectForDevelopmentTest(ContinuousCameraEffect e){ CameraImpulse clean=e==null?null:sanitize(e.getImpulse()); if(clean==null||!hasProcessableChannel(clean))return Handle.INACTIVE; Handle h=new Handle(clean,safe(e.getStrength(),0,1)); continuous.add(h); return h; }
    public static CameraEffectHandle startContinuousEffect(ContinuousCameraEffect e){ if(!isAvailable()||e==null)return Handle.INACTIVE; CameraImpulse clean=sanitize(e.getImpulse()); if(clean==null||!hasProcessableChannel(clean))return Handle.INACTIVE; if(continuous.size()>=MAX_CONTINUOUS)continuous.remove(0).stop(); Handle h=new Handle(clean,safe(e.getStrength(),0,1)); continuous.add(h); logDebug("camera API continuous effect created id="+h.impulse.getEffectId()+" pitch="+h.impulse.getPitch()+" yaw="+h.impulse.getYaw()+" roll="+h.impulse.getRoll()+" translation=("+h.impulse.getTranslateX()+","+h.impulse.getTranslateY()+","+h.impulse.getTranslateZ()+") fov="+h.impulse.getFov()); return h; }
    public static void update(EntityPlayerSP player){ pitch=yaw=roll=x=y=z=fov=0; tick(impulses,false,player); for(int n=continuous.size()-1;n>=0;n--){Handle h=continuous.get(n); if(!h.active){continuous.remove(n);continue;} if(h.enabled) contribute(h.impulse,h.strength,player,0.6F);} saturateClamp(); }
    public static float getPitch(){return pitch;} public static float getYaw(){return yaw;} public static float getRoll(){return roll;} public static float getX(){return x;} public static float getY(){return y;} public static float getZ(){return z;} public static float getFov(){return fov;}
    public static void reset(){impulses.clear(); continuous.clear(); pitch=yaw=roll=x=y=z=fov=0;}
    private static void tick(ArrayList<Active> list, boolean cont, EntityPlayerSP p){ for(int n=list.size()-1;n>=0;n--){Active a=list.get(n); a.age+=1F/20F; float d=Math.max(0.05F,a.impulse.getDuration()); if(a.age>d){list.remove(n); logDebug("camera API impulse expired id="+a.impulse.getEffectId()); continue;} float t=a.age/d; float env=t<safe(a.impulse.getAttackTime(),0,d)/d? t/Math.max(0.01F,a.impulse.getAttackTime()/d) : 1F-t; contribute(a.impulse, safe(env,0,1)*a.strength,p,1F);} }
    private static void contribute(CameraImpulse i,float s,EntityPlayerSP p,float contScale){ float fall=falloff(i,p); float osc=i.getFrequency()>0?(float)Math.sin(System.nanoTime()/1000000000.0D*i.getFrequency()*6.28318D):1F; float k=s*fall*osc*priority(i.getPriority())*contScale; pitch+=i.getPitch()*k; yaw+=i.getYaw()*k; roll+=i.getRoll()*k; x+=i.getTranslateX()*k; y+=i.getTranslateY()*k; z+=i.getTranslateZ()*k; fov+=i.getFov()*k; if(Combatives.logger!=null&&CombativesConfig.verboseCameraDebug)Combatives.logger.info("camera API active effect id={} pitch={} yaw={} roll={} translation=({},{},{}) fov={} sampleScale={}", i.getEffectId(), i.getPitch()*k, i.getYaw()*k, i.getRoll()*k, i.getTranslateX()*k, i.getTranslateY()*k, i.getTranslateZ()*k, i.getFov()*k, k); }
    private static CameraImpulse preset(CameraEffectType t,CameraEffectContext c,float s){ String id="combatives:"+t.name().toLowerCase(Locale.ROOT); CameraImpulse.Builder b=CameraImpulse.builder(id).duration(t==CameraEffectType.ENVIRONMENTAL_RUMBLE?1.2F:0.35F).priority(t==CameraEffectType.EXPLOSION?CameraPriority.STRONG:CameraPriority.NORMAL); if(c!=null){ if(c.getSourceEntity()!=null)b.sourceEntity(c.getSourceEntity()); if(c.hasPosition())b.position(c.getX(),c.getY(),c.getZ()); } switch(t){case EXPLOSION:b.rotation(8*s,0,4*s).translation(0,0.16F*s,-0.14F*s).fov(2*s);break;case LANDING:b.rotation(6*s,0,1*s).translation(0,-0.12F*s,-0.05F*s);break;case WEAPON_FIRE:b.rotation(-2*s,0,0.8F*s).translation(0,0,-0.04F*s).duration(0.18F);break;case VEHICLE_COLLISION:b.rotation(7*s,0,3*s).translation(0,0.12F*s,-0.12F*s);break;case ENVIRONMENTAL_RUMBLE:b.rotation(1.2F*s,0,1.2F*s).translation(0.02F*s,0.025F*s,0).oscillationFrequency(8F);break;default:b.rotation(3*s,0,1.5F*s).translation(0,0.05F*s,-0.04F*s);} return b.build(); }
    private static CameraImpulse sanitize(CameraImpulse i){ if(i==null||!validId(i.getEffectId()))return null; if(!finite(i.getPitch())||!finite(i.getYaw())||!finite(i.getRoll())||!finite(i.getTranslateX())||!finite(i.getTranslateY())||!finite(i.getTranslateZ())||!finite(i.getFov()))return null; if(!finite(i.getDuration())||i.getDuration()<=0||i.getDuration()>30||!finite(i.getAttackTime())||i.getAttackTime()<0||!finite(i.getFrequency())||i.getFrequency()<0||i.getFrequency()>80)return null; if(i.hasPosition()&&(!finite((float)i.getX())||!finite((float)i.getY())||!finite((float)i.getZ())))return null; return i; }
    private static boolean hasProcessableChannel(CameraImpulse i){return i.getPitch()!=0||i.getYaw()!=0||i.getRoll()!=0||i.getTranslateX()!=0||i.getTranslateY()!=0||i.getTranslateZ()!=0||i.getFov()!=0;}
    private static boolean validId(String id){return id!=null&&id.matches("[a-z0-9_.-]+:[a-z0-9_/.-]+");} private static boolean finite(float v){return !Float.isNaN(v)&&!Float.isInfinite(v);} private static float safe(float v,float min,float max){return finite(v)?Math.max(min,Math.min(max,v)):min;} private static boolean reject(String r){log("camera API submission rejected: "+r);return false;}
    private static float falloff(CameraImpulse i,EntityPlayerSP p){ if(p==null)return 1; double sx,sy,sz; if(i.hasPosition()){sx=i.getX(); sy=i.getY(); sz=i.getZ();} else if(i.getSourceEntity()!=null){sx=i.getSourceEntity().posX; sy=i.getSourceEntity().posY+i.getSourceEntity().height*0.5D; sz=i.getSourceEntity().posZ;} else return 1; double dx=p.posX-sx,dy=p.posY+p.getEyeHeight()-sy,dz=p.posZ-sz; double d=Math.sqrt(dx*dx+dy*dy+dz*dz); float out=safe(1F-(float)(d/32D),0,1); if(Combatives.logger!=null&&CombativesConfig.verboseCameraDebug)Combatives.logger.info("camera API positional falloff id={} distance={} response={}", i.getEffectId(), d, out); return out; }
    private static void saturateClamp(){ pitch=clampSat(pitch,10); yaw=clamp(clampSat(yaw,CombativesConfig.maxCameraYawDegrees),-CombativesConfig.maxCameraYawDegrees,CombativesConfig.maxCameraYawDegrees); roll=clampSat(roll,6); x=clampSat(x,0.18F); y=clampSat(y,0.22F); z=clampSat(z,0.18F); fov=clampSat(fov,5); if(Combatives.logger!=null&&CombativesConfig.verboseCameraDebug)Combatives.logger.info("camera API final output pitch={} yaw={} roll={} translation=({},{},{}) fov={}", pitch,yaw,roll,x,y,z,fov); }
    private static float clamp(float v,float min,float max){return v<min?min:v>max?max:v;} private static float clampSat(float v,float max){return max<=0?0:(float)Math.tanh(v/max)*max;} private static float priority(CameraPriority p){return p==CameraPriority.CINEMATIC?1.35F:p==CameraPriority.CRITICAL?1.2F:p==CameraPriority.STRONG?1.1F:p==CameraPriority.BACKGROUND?0.65F:1F;}
    private static boolean resolveStacking(ArrayList<Active> list,CameraImpulse i){ if(i.getStackingMode()==CameraStackingMode.ADD)return true; for(int n=list.size()-1;n>=0;n--) if(list.get(n).impulse.getEffectId().equals(i.getEffectId())){ if(i.getStackingMode()==CameraStackingMode.IGNORE_IF_ACTIVE){logDebug("camera API stacking ignored id="+i.getEffectId());return false;} if(i.getStackingMode()==CameraStackingMode.REFRESH_SAME_ID){list.get(n).age=0; logDebug("camera API stacking refreshed id="+i.getEffectId()); return false;} list.remove(n); logDebug("camera API stacking replaced id="+i.getEffectId()); } return true; }
    private static void log(String m){if(Combatives.logger!=null)Combatives.logger.info(m);} private static void logDebug(String m){if(Combatives.logger!=null&&CombativesConfig.debugCamera)Combatives.logger.info(m);} private static final class Active{CameraImpulse impulse;float age,strength;Active(CameraImpulse i,float s){impulse=i;strength=s;}}
    private static final class Handle implements CameraEffectHandle{static final Handle INACTIVE=new Handle(null,0); CameraImpulse impulse; float strength; boolean active=true,enabled=true; Handle(CameraImpulse i,float s){impulse=i;strength=s;if(i==null)active=false;} public boolean isActive(){return active;} public void setStrength(float s){strength=safe(s,0,1);} public void setPosition(double x,double y,double z){ if(impulse!=null) impulse=CameraImpulse.builder(impulse.getEffectId()).position(x,y,z).rotation(impulse.getPitch(),impulse.getYaw(),impulse.getRoll()).translation(impulse.getTranslateX(),impulse.getTranslateY(),impulse.getTranslateZ()).fov(impulse.getFov()).duration(impulse.getDuration()).attackTime(impulse.getAttackTime()).decayType(impulse.getDecayType()).oscillationFrequency(impulse.getFrequency()).priority(impulse.getPriority()).stackingMode(impulse.getStackingMode()).build();} public void setEnabled(boolean e){enabled=e;} public void stop(){active=false;}}
}
